dotnet/Puppies.Web/Models/ErrorViewModel.cs
using System;

namespace Puppies.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

dotnet/Puppies.Web/Models/Puppy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Puppies.Web.Models
{
    public class Puppy
    {
        public Puppy() {}

        public Puppy(string name, int weight, string gender, bool paperTrained) {
            Name = name;
            Weight = weight;
            Gender = gender;
            PaperTrained = paperTrained;
        }

        public Puppy(int id, string name, int weight, string gender, bool paperTrained)
        {
            Id = id;
            Name = name;
            Weight = weight;
            Gender = gender;
            PaperTrained = paperTrained;
        }
        public int Id { get; set; }

        public string Name { get; set; }

        public int Weight { get; set; }

        public string Gender { get; set; }

        public bool PaperTrained { get; set; }

    }
}

dotnet/Puppies.Web/Controllers/PuppiesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Puppies.Web.DAL;
using Puppies.Web.Models;

namespace Puppies.Web.Controllers
{
    public class PuppiesController : Controller
    {       
        public PuppiesController()
        {
            
        }
    }
}

dotnet/Puppies.Web/Views/Puppies/Detail.cshtml
@model Puppy
@{
    ViewData["Title"] = Model.Name;
}

<h1>@Model.Name <small>@Model.Gender</small></h1>

<p>@Model.Name is a wonderful dog who weighs @Model.Weight lbs and is
@if(!Model.PaperTrained)
{
    <text> NOT </text>
}
paper trained.</p>

dotnet/Puppies.Web/Views/Puppies/Index.cshtml
@model IList<Puppy>
@{
    ViewData["Title"] = "Puppies!!!";
}

<h1>Puppies!!!</h1>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Weight</th>
        <th>Gender</th>
        <th>Paper Trained?</th>
    </tr>

    <tr>
        <td>
            Example Name
        </td>
        <td>
            0 lbs
        </td>
        <td>
            Example
        </td>
        <td>
            Maybe
        </td>
    </tr>

</table>
<fieldset>
<legend>Add a new puppy</legend>

<form class="form" asp-area="" asp-controller="Puppies" asp-action="Save" method="POST">
    <div class="form-group">
        <input type="text" class="form-control" name="Name" placeholder="Name">
    </div>
    <div class="form-group">
        <input type="number" class="form-control" name="Weight" placeholder="Weight">
    </div>
    <div class="checkbox">
        <label>
            <input type="radio" name="Gender" value="Male"> Male
        </label>
        <label>
            <input type="radio" name="Gender" value="Female"> Female
        </label>
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="PaperTrained" value="true"> Paper Trained</label>
    </div>
    <input class="btn btn-default" name="submit" value="Save Puppy!" type="submit" />
</form>
</fieldset>

dotnet/Puppies.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Puppies!!!</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Puppies" asp-action="Index" class="navbar-brand">Puppies.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Puppies.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>